# -*- coding: utf-8 -*-

{
    'name': 'Pragtech University Dashboard',
    'version': '16.0.0.0.2',
    'category': 'Education',
    'summary': 'Dashboard',
    'complexity': "easy",
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'http://www.pragtech.co.in',
    'depends': ['base', 'mail', 'product', 'account', 'l10n_in', 'board', 'portal', 'website',],
    'data': [
        'security/school_security.xml',
        'security/ir.model.access.csv',
        'data/enroll_sequence.xml',
        'views/school_dashboard_view.xml',
        'views/academic_year_view.xml',
        'views/student_master_view.xml',
        'views/teacher_master_view.xml',
        'views/class_subjects_view.xml',
        'views/class_room_view.xml',
        'views/admission_master_view.xml',
        'views/account_move_view.xml',
        'views/enroll_mechanism_view.xml',
        'views/create_timetables_view.xml',
        'views/timetable_period_time_view.xml',
        'views/students_attendance_view.xml',
        # 'views/assignment_master_view.xml',
        # 'views/completed_assignment_view.xml',
        'views/exam_master_view.xml',
        'views/exam_attendance_view.xml',
        'views/fees_management_view.xml',
        'views/mark_sheets_view.xml',
        'views/grade_master_view.xml',
        'views/guardian_master_view.xml',
        'views/attendances_student_portal_template.xml',
        'views/exams_student_portal_template.xml',
        'views/mark_sheet_student_portal_template.xml',
        'views/assignments_student_portal_template.xml',
        'views/student_class_timetable_portal_template.xml',
        'views/school_dashboard_menu.xml',
        'views/student_attendance_report_view.xml',
        'report/report_marksheet.xml',
        'report/report_attendance.xml',
        'report/report_student_attendance.xml',
        'report/report_menu.xml',
        'wizard/wizard_student_attendance_report.xml',
    ],
    'images': [
        'static/description/pragtech_logo.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'assets': {
        'web.assets_frontend': [
            'pragtech_university_dashboard/static/src/scss/assignments_submission_form_template.scss',
        ],
        'web.assets_backend': [
            'pragtech_university_dashboard/static/src/js/dashboard.js',
            'pragtech_university_dashboard/static/src/css/style.css',
            'pragtech_university_dashboard/static/src/scss/assignments_submission_form_template.scss',
            'pragtech_university_dashboard/static/src/xml/**/*'

        ],
    },
    'license': 'LGPL-3',

}
